server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

logging:
  level:
    com.springboot.rest.h2.springbootrestserviceh2: DEBUG
    org.springframework.web: DEBUG
    
    
    